### ISSUE TITLE
关于FLIR数据集

### ISSUE THREAD

**Issue by ciderjoy** [XueZ-phd/Efficient-RGB-T-Early-Fusion-Detection#2]
作者团队您好！
根据文献Robust Environment Perception for Automated Driving: A Unified Learning Pipeline for Visual-Infrared Object Detection，FLIR被（实际）划分为train(7381),val(1056),test(2111)。请问您的文献中有关FLIR实验结果，是**仅通过train集训练，val在训练中验证，报告的是测试集test上的精度吗**？还是说将train和val混合训练，报告test上的精度呢？
期待您的回复

**Comment by XueZ-phd** [comment]
感谢您关注我们的工作！

文中FLIR数据集上的结果是在train+val上训练，在test上测试获得的。
